[tool.black]
line-length = 120

[tool.bumpversion]
current_version = "0.6.1"
commit = true
tag = true
tag_name = "{new_version}"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
sign_tags = false
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
message = "Bump version: {current_version} → {new_version}"
moveable_tags = []
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

[[tool.bumpversion.files]]
filename = 'CHANGES.rst'
search = "\\(unreleased\\)$"
replace = "{new_version} ({now:%Y-%m-%d})"
regex = true

[[tool.bumpversion.files]]
filename = "hcf_backend/__init__.py"

[[tool.bumpversion.files]]
filename = "setup.py"
search = "version=\"{current_version}"
replace = "version=\"{new_version}"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning:scrapinghub.hubstorage.serialization"
]
