[tool.black]
line-length = 120

[tool.bumpversion]
current_version = "0.5.3"
commit = true
tag = true
tag_name = "{new_version}"

[[tool.bumpversion.files]]
filename = 'CHANGELOG.rst'
search = "\\(unreleased\\)$"
replace = "({now:%Y-%m-%d})"
regex = true

[[tool.bumpversion.files]]
filename = "hcf_backend/__init__.py"

[[tool.bumpversion.files]]
filename = "setup.py"
search = "version=\"{current_version}"
replace = "version=\"{new_version}"
